// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.fuhu.demo.protobuf;

public final class MyBaseProto {
  private MyBaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ONE = 1;</code>
     */
    ONE(1),
    /**
     * <code>TWO = 2;</code>
     */
    TWO(2),
    /**
     * <code>THREE = 3;</code>
     */
    THREE(3),
    ;

    /**
     * <code>ONE = 1;</code>
     */
    public static final int ONE_VALUE = 1;
    /**
     * <code>TWO = 2;</code>
     */
    public static final int TWO_VALUE = 2;
    /**
     * <code>THREE = 3;</code>
     */
    public static final int THREE_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 1: return ONE;
        case 2: return TWO;
        case 3: return THREE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fuhu.demo.protobuf.MyBaseProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Type)
  }

  public interface BodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Body)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    java.util.List<java.lang.String>
        getLList();
    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    int getLCount();
    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    java.lang.String getL(int index);
    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    com.google.protobuf.ByteString
        getLBytes(int index);

    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */
    int getMCount();
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */
    boolean containsM(
        java.lang.String key);
    /**
     * Use {@link #getMMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getM();
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMMap();
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */

    java.lang.String getMOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */

    java.lang.String getMOrThrow(
        java.lang.String key);

    /**
     * <code>optional .Type type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional .Type type = 3;</code>
     */
    com.fuhu.demo.protobuf.MyBaseProto.Type getType();
  }
  /**
   * Protobuf type {@code Body}
   */
  public  static final class Body extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Body)
      BodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Body.newBuilder() to construct.
    private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Body() {
      l_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      type_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Body(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                l_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              l_.add(bs);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                m_ = com.google.protobuf.MapField.newMapField(
                    MDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              m__ = input.readMessage(
                  MDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              m_.getMutableMap().put(
                  m__.getKey(), m__.getValue());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.fuhu.demo.protobuf.MyBaseProto.Type value = com.fuhu.demo.protobuf.MyBaseProto.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          l_ = l_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuhu.demo.protobuf.MyBaseProto.internal_static_Body_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetM();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuhu.demo.protobuf.MyBaseProto.internal_static_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuhu.demo.protobuf.MyBaseProto.Body.class, com.fuhu.demo.protobuf.MyBaseProto.Body.Builder.class);
    }

    private int bitField0_;
    public static final int L_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList l_;
    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getLList() {
      return l_;
    }
    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    public int getLCount() {
      return l_.size();
    }
    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    public java.lang.String getL(int index) {
      return l_.get(index);
    }
    /**
     * <pre>
     * repeated 列表
     * </pre>
     *
     * <code>repeated string l = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLBytes(int index) {
      return l_.getByteString(index);
    }

    public static final int M_FIELD_NUMBER = 2;
    private static final class MDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.fuhu.demo.protobuf.MyBaseProto.internal_static_Body_MEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> m_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetM() {
      if (m_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MDefaultEntryHolder.defaultEntry);
      }
      return m_;
    }

    public int getMCount() {
      return internalGetM().getMap().size();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */

    public boolean containsM(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetM().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getM() {
      return getMMap();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMMap() {
      return internalGetM().getMap();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */

    public java.lang.String getMOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetM().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, string&gt; m = 2;</code>
     */

    public java.lang.String getMOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetM().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional .Type type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Type type = 3;</code>
     */
    public com.fuhu.demo.protobuf.MyBaseProto.Type getType() {
      @SuppressWarnings("deprecation")
      com.fuhu.demo.protobuf.MyBaseProto.Type result = com.fuhu.demo.protobuf.MyBaseProto.Type.valueOf(type_);
      return result == null ? com.fuhu.demo.protobuf.MyBaseProto.Type.ONE : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < l_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, l_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetM(),
          MDefaultEntryHolder.defaultEntry,
          2);
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < l_.size(); i++) {
          dataSize += computeStringSizeNoTag(l_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getLList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetM().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        m__ = MDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, m__);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fuhu.demo.protobuf.MyBaseProto.Body)) {
        return super.equals(obj);
      }
      com.fuhu.demo.protobuf.MyBaseProto.Body other = (com.fuhu.demo.protobuf.MyBaseProto.Body) obj;

      boolean result = true;
      result = result && getLList()
          .equals(other.getLList());
      result = result && internalGetM().equals(
          other.internalGetM());
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLCount() > 0) {
        hash = (37 * hash) + L_FIELD_NUMBER;
        hash = (53 * hash) + getLList().hashCode();
      }
      if (!internalGetM().getMap().isEmpty()) {
        hash = (37 * hash) + M_FIELD_NUMBER;
        hash = (53 * hash) + internalGetM().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.Body parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fuhu.demo.protobuf.MyBaseProto.Body prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Body}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Body)
        com.fuhu.demo.protobuf.MyBaseProto.BodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuhu.demo.protobuf.MyBaseProto.internal_static_Body_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetM();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableM();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuhu.demo.protobuf.MyBaseProto.internal_static_Body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuhu.demo.protobuf.MyBaseProto.Body.class, com.fuhu.demo.protobuf.MyBaseProto.Body.Builder.class);
      }

      // Construct using com.fuhu.demo.protobuf.MyBaseProto.Body.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        l_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableM().clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuhu.demo.protobuf.MyBaseProto.internal_static_Body_descriptor;
      }

      @java.lang.Override
      public com.fuhu.demo.protobuf.MyBaseProto.Body getDefaultInstanceForType() {
        return com.fuhu.demo.protobuf.MyBaseProto.Body.getDefaultInstance();
      }

      @java.lang.Override
      public com.fuhu.demo.protobuf.MyBaseProto.Body build() {
        com.fuhu.demo.protobuf.MyBaseProto.Body result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fuhu.demo.protobuf.MyBaseProto.Body buildPartial() {
        com.fuhu.demo.protobuf.MyBaseProto.Body result = new com.fuhu.demo.protobuf.MyBaseProto.Body(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          l_ = l_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.l_ = l_;
        result.m_ = internalGetM();
        result.m_.makeImmutable();
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuhu.demo.protobuf.MyBaseProto.Body) {
          return mergeFrom((com.fuhu.demo.protobuf.MyBaseProto.Body)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuhu.demo.protobuf.MyBaseProto.Body other) {
        if (other == com.fuhu.demo.protobuf.MyBaseProto.Body.getDefaultInstance()) return this;
        if (!other.l_.isEmpty()) {
          if (l_.isEmpty()) {
            l_ = other.l_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLIsMutable();
            l_.addAll(other.l_);
          }
          onChanged();
        }
        internalGetMutableM().mergeFrom(
            other.internalGetM());
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuhu.demo.protobuf.MyBaseProto.Body parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuhu.demo.protobuf.MyBaseProto.Body) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList l_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          l_ = new com.google.protobuf.LazyStringArrayList(l_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getLList() {
        return l_.getUnmodifiableView();
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public int getLCount() {
        return l_.size();
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public java.lang.String getL(int index) {
        return l_.get(index);
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLBytes(int index) {
        return l_.getByteString(index);
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public Builder setL(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLIsMutable();
        l_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public Builder addL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLIsMutable();
        l_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public Builder addAllL(
          java.lang.Iterable<java.lang.String> values) {
        ensureLIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, l_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public Builder clearL() {
        l_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * repeated 列表
       * </pre>
       *
       * <code>repeated string l = 1;</code>
       */
      public Builder addLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLIsMutable();
        l_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> m_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetM() {
        if (m_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MDefaultEntryHolder.defaultEntry);
        }
        return m_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableM() {
        onChanged();;
        if (m_ == null) {
          m_ = com.google.protobuf.MapField.newMapField(
              MDefaultEntryHolder.defaultEntry);
        }
        if (!m_.isMutable()) {
          m_ = m_.copy();
        }
        return m_;
      }

      public int getMCount() {
        return internalGetM().getMap().size();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, string&gt; m = 2;</code>
       */

      public boolean containsM(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetM().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getM() {
        return getMMap();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, string&gt; m = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getMMap() {
        return internalGetM().getMap();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, string&gt; m = 2;</code>
       */

      public java.lang.String getMOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetM().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, string&gt; m = 2;</code>
       */

      public java.lang.String getMOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetM().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearM() {
        internalGetMutableM().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, string&gt; m = 2;</code>
       */

      public Builder removeM(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableM().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableM() {
        return internalGetMutableM().getMutableMap();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, string&gt; m = 2;</code>
       */
      public Builder putM(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableM().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, string&gt; m = 2;</code>
       */

      public Builder putAllM(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableM().getMutableMap()
            .putAll(values);
        return this;
      }

      private int type_ = 1;
      /**
       * <code>optional .Type type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Type type = 3;</code>
       */
      public com.fuhu.demo.protobuf.MyBaseProto.Type getType() {
        @SuppressWarnings("deprecation")
        com.fuhu.demo.protobuf.MyBaseProto.Type result = com.fuhu.demo.protobuf.MyBaseProto.Type.valueOf(type_);
        return result == null ? com.fuhu.demo.protobuf.MyBaseProto.Type.ONE : result;
      }
      /**
       * <code>optional .Type type = 3;</code>
       */
      public Builder setType(com.fuhu.demo.protobuf.MyBaseProto.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Type type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 1;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Body)
    }

    // @@protoc_insertion_point(class_scope:Body)
    private static final com.fuhu.demo.protobuf.MyBaseProto.Body DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fuhu.demo.protobuf.MyBaseProto.Body();
    }

    public static com.fuhu.demo.protobuf.MyBaseProto.Body getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Body>
        PARSER = new com.google.protobuf.AbstractParser<Body>() {
      @java.lang.Override
      public Body parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Body(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Body> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Body> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fuhu.demo.protobuf.MyBaseProto.Body getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BaseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *   默认值，表示成员只有0个或者1个
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     *   默认值，表示成员只有0个或者1个
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     * </pre>
     *
     * <code>required string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <pre>
     * </pre>
     *
     * <code>required string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <pre>
     * </pre>
     *
     * <code>required string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .Body result = 3;</code>
     */
    boolean hasResult();
    /**
     * <code>optional .Body result = 3;</code>
     */
    com.fuhu.demo.protobuf.MyBaseProto.Body getResult();
    /**
     * <code>optional .Body result = 3;</code>
     */
    com.fuhu.demo.protobuf.MyBaseProto.BodyOrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code BaseProto}
   */
  public  static final class BaseProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseProto)
      BaseProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseProto.newBuilder() to construct.
    private BaseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseProto() {
      code_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msg_ = bs;
              break;
            }
            case 26: {
              com.fuhu.demo.protobuf.MyBaseProto.Body.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(com.fuhu.demo.protobuf.MyBaseProto.Body.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuhu.demo.protobuf.MyBaseProto.internal_static_BaseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuhu.demo.protobuf.MyBaseProto.internal_static_BaseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuhu.demo.protobuf.MyBaseProto.BaseProto.class, com.fuhu.demo.protobuf.MyBaseProto.BaseProto.Builder.class);
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *   默认值，表示成员只有0个或者1个
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *   默认值，表示成员只有0个或者1个
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <pre>
     * </pre>
     *
     * <code>required string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>required string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>required string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private com.fuhu.demo.protobuf.MyBaseProto.Body result_;
    /**
     * <code>optional .Body result = 3;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Body result = 3;</code>
     */
    public com.fuhu.demo.protobuf.MyBaseProto.Body getResult() {
      return result_ == null ? com.fuhu.demo.protobuf.MyBaseProto.Body.getDefaultInstance() : result_;
    }
    /**
     * <code>optional .Body result = 3;</code>
     */
    public com.fuhu.demo.protobuf.MyBaseProto.BodyOrBuilder getResultOrBuilder() {
      return result_ == null ? com.fuhu.demo.protobuf.MyBaseProto.Body.getDefaultInstance() : result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getResult());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getResult());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fuhu.demo.protobuf.MyBaseProto.BaseProto)) {
        return super.equals(obj);
      }
      com.fuhu.demo.protobuf.MyBaseProto.BaseProto other = (com.fuhu.demo.protobuf.MyBaseProto.BaseProto) obj;

      boolean result = true;
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && (getCode()
            == other.getCode());
      }
      result = result && (hasMsg() == other.hasMsg());
      if (hasMsg()) {
        result = result && getMsg()
            .equals(other.getMsg());
      }
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && getResult()
            .equals(other.getResult());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fuhu.demo.protobuf.MyBaseProto.BaseProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseProto)
        com.fuhu.demo.protobuf.MyBaseProto.BaseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuhu.demo.protobuf.MyBaseProto.internal_static_BaseProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuhu.demo.protobuf.MyBaseProto.internal_static_BaseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuhu.demo.protobuf.MyBaseProto.BaseProto.class, com.fuhu.demo.protobuf.MyBaseProto.BaseProto.Builder.class);
      }

      // Construct using com.fuhu.demo.protobuf.MyBaseProto.BaseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (resultBuilder_ == null) {
          result_ = null;
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuhu.demo.protobuf.MyBaseProto.internal_static_BaseProto_descriptor;
      }

      @java.lang.Override
      public com.fuhu.demo.protobuf.MyBaseProto.BaseProto getDefaultInstanceForType() {
        return com.fuhu.demo.protobuf.MyBaseProto.BaseProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.fuhu.demo.protobuf.MyBaseProto.BaseProto build() {
        com.fuhu.demo.protobuf.MyBaseProto.BaseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fuhu.demo.protobuf.MyBaseProto.BaseProto buildPartial() {
        com.fuhu.demo.protobuf.MyBaseProto.BaseProto result = new com.fuhu.demo.protobuf.MyBaseProto.BaseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuhu.demo.protobuf.MyBaseProto.BaseProto) {
          return mergeFrom((com.fuhu.demo.protobuf.MyBaseProto.BaseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuhu.demo.protobuf.MyBaseProto.BaseProto other) {
        if (other == com.fuhu.demo.protobuf.MyBaseProto.BaseProto.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCode()) {
          return false;
        }
        if (!hasMsg()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuhu.demo.protobuf.MyBaseProto.BaseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuhu.demo.protobuf.MyBaseProto.BaseProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <pre>
       *   默认值，表示成员只有0个或者1个
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *   默认值，表示成员只有0个或者1个
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *   默认值，表示成员只有0个或者1个
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *   默认值，表示成员只有0个或者1个
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>required string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>required string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      private com.fuhu.demo.protobuf.MyBaseProto.Body result_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fuhu.demo.protobuf.MyBaseProto.Body, com.fuhu.demo.protobuf.MyBaseProto.Body.Builder, com.fuhu.demo.protobuf.MyBaseProto.BodyOrBuilder> resultBuilder_;
      /**
       * <code>optional .Body result = 3;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      public com.fuhu.demo.protobuf.MyBaseProto.Body getResult() {
        if (resultBuilder_ == null) {
          return result_ == null ? com.fuhu.demo.protobuf.MyBaseProto.Body.getDefaultInstance() : result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      public Builder setResult(com.fuhu.demo.protobuf.MyBaseProto.Body value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      public Builder setResult(
          com.fuhu.demo.protobuf.MyBaseProto.Body.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      public Builder mergeResult(com.fuhu.demo.protobuf.MyBaseProto.Body value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              result_ != null &&
              result_ != com.fuhu.demo.protobuf.MyBaseProto.Body.getDefaultInstance()) {
            result_ =
              com.fuhu.demo.protobuf.MyBaseProto.Body.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = null;
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      public com.fuhu.demo.protobuf.MyBaseProto.Body.Builder getResultBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      public com.fuhu.demo.protobuf.MyBaseProto.BodyOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_ == null ?
              com.fuhu.demo.protobuf.MyBaseProto.Body.getDefaultInstance() : result_;
        }
      }
      /**
       * <code>optional .Body result = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.fuhu.demo.protobuf.MyBaseProto.Body, com.fuhu.demo.protobuf.MyBaseProto.Body.Builder, com.fuhu.demo.protobuf.MyBaseProto.BodyOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.fuhu.demo.protobuf.MyBaseProto.Body, com.fuhu.demo.protobuf.MyBaseProto.Body.Builder, com.fuhu.demo.protobuf.MyBaseProto.BodyOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseProto)
    }

    // @@protoc_insertion_point(class_scope:BaseProto)
    private static final com.fuhu.demo.protobuf.MyBaseProto.BaseProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fuhu.demo.protobuf.MyBaseProto.BaseProto();
    }

    public static com.fuhu.demo.protobuf.MyBaseProto.BaseProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BaseProto>
        PARSER = new com.google.protobuf.AbstractParser<BaseProto>() {
      @java.lang.Override
      public BaseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fuhu.demo.protobuf.MyBaseProto.BaseProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Body_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Body_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Body_MEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Body_MEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\"i\n\004Body\022\t\n\001l\030\001 \003(\t\022\027\n\001m\030\002 \003(" +
      "\0132\014.Body.MEntry\022\023\n\004type\030\003 \001(\0162\005.Type\032(\n\006" +
      "MEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"=" +
      "\n\tBaseProto\022\014\n\004code\030\001 \002(\005\022\013\n\003msg\030\002 \002(\t\022\025" +
      "\n\006result\030\003 \001(\0132\005.Body*#\n\004Type\022\007\n\003ONE\020\001\022\007" +
      "\n\003TWO\020\002\022\t\n\005THREE\020\003B%\n\026com.fuhu.demo.prot" +
      "obufB\013MyBaseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Body_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Body_descriptor,
        new java.lang.String[] { "L", "M", "Type", });
    internal_static_Body_MEntry_descriptor =
      internal_static_Body_descriptor.getNestedTypes().get(0);
    internal_static_Body_MEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Body_MEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_BaseProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BaseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseProto_descriptor,
        new java.lang.String[] { "Code", "Msg", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
